// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#ifdef OMIT_EMOJI_FONTS
#define LEXENDDECA_8_FONT_ID (-2022789252)
#else
#define LEXENDDECA_8_FONT_ID (-2044145940)
#endif
#ifdef OMIT_EMOJI_FONTS
#define LEXENDDECA_9_FONT_ID (-1206441199)
#else
#define LEXENDDECA_9_FONT_ID (2003672599)
#endif
#ifdef OMIT_EMOJI_FONTS
#define LEXENDDECA_10_FONT_ID (848942201)
#else
#define LEXENDDECA_10_FONT_ID (1144677629)
#endif
#ifdef OMIT_EMOJI_FONTS
#define LEXENDDECA_12_FONT_ID (998273723)
#else
#define LEXENDDECA_12_FONT_ID (1926983473)
#endif
#ifdef OMIT_EMOJI_FONTS
#define LEXENDDECA_14_FONT_ID (-1351448868)
#else
#define LEXENDDECA_14_FONT_ID (-1406445118)
#endif
#ifdef OMIT_EMOJI_FONTS
#define LEXENDDECA_16_FONT_ID (-1656483080)
#else
#define LEXENDDECA_16_FONT_ID (2019090238)
#endif
#ifdef OMIT_EMOJI_FONTS
#define LEXENDDECA_18_FONT_ID (-1005241028)
#else
#define LEXENDDECA_18_FONT_ID (1302402945)
#endif
#ifdef OMIT_EMOJI_FONTS
#define LEXENDDECA_20_FONT_ID (-1863552944)
#else
#define LEXENDDECA_20_FONT_ID (-1459152267)
#endif
#ifdef OMIT_EMOJI_FONTS
#define CHAREINK_8_FONT_ID (-2130262487)
#else
#define CHAREINK_8_FONT_ID (312370057)
#endif
#ifdef OMIT_EMOJI_FONTS
#define CHAREINK_9_FONT_ID (-1667541806)
#else
#define CHAREINK_9_FONT_ID (631165824)
#endif
#ifdef OMIT_EMOJI_FONTS
#define CHAREINK_10_FONT_ID (1310190783)
#else
#define CHAREINK_10_FONT_ID (-944299713)
#endif
#ifdef OMIT_EMOJI_FONTS
#define CHAREINK_12_FONT_ID (865209132)
#else
#define CHAREINK_12_FONT_ID (562864807)
#endif
#ifdef OMIT_EMOJI_FONTS
#define CHAREINK_14_FONT_ID (892739170)
#else
#define CHAREINK_14_FONT_ID (-1176545950)
#endif
#ifdef OMIT_EMOJI_FONTS
#define CHAREINK_16_FONT_ID (1747724046)
#else
#define CHAREINK_16_FONT_ID (-1477679466)
#endif
#ifdef OMIT_EMOJI_FONTS
#define CHAREINK_18_FONT_ID (438073136)
#else
#define CHAREINK_18_FONT_ID (-787708407)
#endif
#ifdef OMIT_EMOJI_FONTS
#define CHAREINK_20_FONT_ID (1321537766)
#else
#define CHAREINK_20_FONT_ID (-390579825)
#endif
#ifdef OMIT_EMOJI_FONTS
#define LATO_10_FONT_ID (-1487243402)
#else
#define LATO_10_FONT_ID (1956817565)
#endif
#ifdef OMIT_EMOJI_FONTS
#define LATO_12_FONT_ID (870115970)
#else
#define LATO_12_FONT_ID (-1624546516)
#endif
#ifdef OMIT_EMOJI_FONTS
#define LATO_14_FONT_ID (1922207624)
#else
#define LATO_14_FONT_ID (-285539911)
#endif
#ifdef OMIT_EMOJI_FONTS
#define LATO_16_FONT_ID (469998900)
#else
#define LATO_16_FONT_ID (-1248975330)
#endif
#define UI_10_FONT_ID (971628580)
#define UI_12_FONT_ID (1618379298)
#define SMALL_FONT_ID (1851589260)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(LEXENDDECA_8_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_9_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_20_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_8_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_9_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_20_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LATO_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LATO_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LATO_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LATO_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
